"""add photo to drone

Revision ID: f087e9c3e3be
Revises: 85fed3cbaa65
Create Date: 2025-06-20 15:55:25.542728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f087e9c3e3be'
down_revision: Union[str, None] = '85fed3cbaa65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone', sa.Column('photo', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drone', 'photo')
    # ### end Alembic commands ###
